version: 0.4.{build}

pull_requests:
  do_not_increment_build_number: false
  
image: Visual Studio 2019
before_build:
- ps: dotnet restore
build:
  project: EaseLib.sln
  verbosity: minimal

artifacts:
- path: Artifacts\NuGet\*.nupkg
  name: nugets

skip_commits:
  files:
    - '**\*.md'

nuget:
  disable_publish_on_pr: true
  account_feed: false
  project_feed: true

deploy:
- provider: NuGet
  api_key:
    secure: j/i7K4TBOarCsC9rrzZSfTt8ww/51HtYutI0w2mnAcELOuqpQvkLRIDCoaPYYm++
  on:
    branch: master
